In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
voc_size=5000

In [7]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4114, 4677, 4400, 3175],
 [4114, 4677, 4400, 989],
 [4114, 2445, 4400, 411],
 [3963, 770, 1418, 4352, 91],
 [3963, 770, 1418, 4352, 2418],
 [2755, 4114, 2500, 4400, 552],
 [3042, 3349, 2983, 4352]]

In [8]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4114 4677 4400 3175]
 [   0    0    0    0 4114 4677 4400  989]
 [   0    0    0    0 4114 2445 4400  411]
 [   0    0    0 3963  770 1418 4352   91]
 [   0    0    0 3963  770 1418 4352 2418]
 [   0    0    0 2755 4114 2500 4400  552]
 [   0    0    0    0 3042 3349 2983 4352]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Athul VR\OneDrive\Desktop\Simple RNN\myvenv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[[-0.03307307, -0.01463024,  0.01789281,  0.04727796,
          0.03434834, -0.02124016, -0.03028917, -0.02300243,
         -0.04225596, -0.02353515],
        [-0.03307307, -0.01463024,  0.01789281,  0.04727796,
          0.03434834, -0.02124016, -0.03028917, -0.02300243,
         -0.04225596, -0.02353515],
        [-0.03307307, -0.01463024,  0.01789281,  0.04727796,
          0.03434834, -0.02124016, -0.03028917, -0.02300243,
         -0.04225596, -0.02353515],
        [-0.03307307, -0.01463024,  0.01789281,  0.04727796,
          0.03434834, -0.02124016, -0.03028917, -0.02300243,
         -0.04225596, -0.02353515],
        [-0.02549937,  0.04818206,  0.01889798,  0.00405607,
         -0.02221329, -0.03020387, -0.02067076,  0.01543081,
          0.04046288, -0.01424087],
        [-0.01469298,  0.03435249,  0.02190595, -0.01009871,
         -0.03228216, -0.04945889,  0.00695743, -0.01827807,
          0.02585974, -0.04510285],
        [ 0.02679734, -0.02639331,  0.00242778, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 4114, 4677, 4400, 3175], dtype=int32)